name: PR Dedupe

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, closed]


# might not be best practice, just an example
permissions: write-all

jobs:
  pr_dedupe:
    runs-on: macos-14
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Find Similar PRs
        id: pr_dedupe
        uses: cs50victor/pr_dedupe@v1.0.8
        env:
          UPSTASH_VECTOR_REST_URL: https://clever-duckling-90037-us1-vector.upstash.io
          UPSTASH_VECTOR_REST_TOKEN: ${{ secrets.PR_DEDUPE_UPSTASH_VECTOR_REST_TOKEN }}

      - name: Log
        shell: bash
        run: |
             echo ${{ steps.pr_dedupe.outputs.similar_prs }}
             echo ${{ steps.pr_dedupe.outputs.similar_prs_markdown }}

      - name: Find Comment
        if: ${{ steps.pr_dedupe.outputs.similar_prs_markdown != '' }}
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- SIMILAR PRS by PR Dedupe -->"

      - name: Create or update comment
        if: ${{ steps.pr_dedupe.outputs.similar_prs_markdown != '' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Similar PRs
            
            ${{ steps.pr_dedupe.outputs.similar_prs_markdown }}
            
            <!-- SIMILAR PRS by PR Dedupe -->
          edit-mode: replace


