name: PR Dedupe

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, closed]


# might not be best practice, just an example
permissions: write-all

jobs:
  pr_dedupe:
    runs-on: macos-14
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Find Similar PRs
        id: pr_dedupe
        uses: cs50victor/pr_dedupe@v1.0.0
        env:
          UPSTASH_VECTOR_REST_URL: https://clever-duckling-90037-us1-vector.upstash.io
          UPSTASH_VECTOR_REST_TOKEN: ${{ secrets.PR_DEDUPE_UPSTASH_VECTOR_REST_TOKEN }}

      - name: Parse PR Dedupe Output
        id: fmt
        shell: bash
        # formatting the output to markdown
        # this looks horrible but it's equivalent to 
        # import os, sys, json;
        # x = ""
        # for i in json.loads(sys.argv[1])["data"]:
        #     x+="|#" + i["pr_url"].split("pull")[1][1:] + "|{" + str(i["percentage"]) + "}%|\n"
        # if x :
        #     x = f"| PR | Match |\n| ---   | --- |\n{x}"
        # os.environ["GITHUB_OUTPUT"] = f"similar_prs={x}"
        run: python3 -c 'import os, sys, json;x = "".join(["|#" + i["pr_url"].split("pull")[1][1:] + "|{" + str(i["percentage"]) + "}%|\n"for i in json.loads(sys.argv[1])["data"]]);x = f"| PR | Match |\n| ---   | --- |\n{x}" if x else x;os.environ["GITHUB_OUTPUT"] = f"similar_prs={x}";' '${{ steps.pr_dedupe.outputs.similar_prs }}'

      - name: Log
        shell: bash
        run: |
             echo ${{ steps.pr_dedupe.outputs.similar_prs }}
             echo ${{ steps.fmt.outputs.similar_prs }}

      - name: Find Comment
        if: ${{ steps.fmt.outputs.similar_prs != '' }}
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- SIMILAR PRS by PR Dedupe -->"

      - name: Create or update comment
        if: ${{ steps.fmt.outputs.similar_prs != '' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Similar PRs
            
            ${{ steps.fmt.outputs.similar_prs }}
            
            <!-- SIMILAR PRS by PR Dedupe -->
          edit-mode: replace
